---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cookiemonster-cm-config
  namespace: cookiemonster
  labels:
    component: cookiemonster
data:
  config.yaml: |-
    namespace:
      - name: openstack
        resource:
        - kind: deployment
          name: rabbitmq
          target: 1
          interval: 60
          duration: 600
          slack: true
        - kind: deployment
          name:
          target: 1
          interval: 60
          duration: 600
          slack: true
        - kind: daemonset
          name:
          target: 1
          interval: 60
          duration: 600
          slack: true
        - kind: statefulset
          name: mariadb
          target: 1
          interval: 60
          duration: 600
          slack: true
